require('init-packer')
require('keymaps')
require('localconf')
require('neovide')
-- require('indent')


-- require('plugin-config.neodev')
require('lspconf')

require('plugin-config.indent-blankline')
require('plugin-config.gitsigns')
require('plugin-config.noice')
require('plugin-config.langlsp')
-- require('plugin-config.symbols-outline')
require('plugin-config.doom-one')
require('plugin-config.startup')
require('plugin-config.neocomposer')
require('plugin-config.lualine')
require('plugin-config.barbar')
require('plugin-config.telescope')
require('plugin-config.web-tools')
require('plugin-config.treesitter')
require('plugin-config.nvim-tree')
require('plugin-config.bluloco')
require('plugin-config.catppuccin')
require('plugin-config.edgy')
require('plugin-config.marks')

-- require('dap.dap-virtual-text')
-- require('dap.dapui')
-- require('dap.main')

require('funcs.show_help')

